### ISSUE TITLE
Add the ability for users to delete TODO items

### ISSUE THREAD

**Issue by matthewdunsdon** [matthewdunsdon/todo-grad-project-madu#4]
- [x] Give each TODO item in the UI a delete button. Use JavaScript to add a button element and attach it to the ``li`` element.
- [x] Make the delete button calls the server API.
  - [x] ``onclick`` event handler
- [x] Add some style for the delete button.
- [x] Refresh the list of TODO items when the response comes back.
- [x] Handle the case that the request fails.
- [x] To keep the build passing, you'll need to add some end to end tests.
  - [x] The tests can be found in tests/e2e.js.
