### ISSUE TITLE
Add the ability for users to mark TODO items as complete

### ISSUE THREAD

**Issue by matthewdunsdon** [matthewdunsdon/todo-grad-project-madu#6]
-  [x] Add an ``isComplete`` field to new TODO items that is set to ``false``.
-  [x] Add a complete button next to each TODO item.
-  [x] Make the complete button call the update API setting the ``isComplete`` field to ``true``.
-  [x] Update the code that displays TODO items to check the ``isComplete`` field and change the style of the TODO item.
